# Use a imagem oficial do MySQL
FROM mysql:latest

# Defina as variáveis de ambiente
ENV MYSQL_ROOT_PASSWORD=180505
ENV MYSQL_DATABASE=todo_list 
ENV MYSQL_MAJOR=innovation
ENV MYSQL_VERSION=9.0.1-1.el9
ENV MYSQL_SHELL_VERSION=9.0.1-1.el9

# Volume onde o MySQL armazenará os dados
VOLUME /var/lib/mysql

# Porta que o MySQL irá escutar
EXPOSE 3306
